#include "cfd/multiphysics/projection.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace cfd::multiphysics { namespace {
bool barycentric(const cfd::fem::Node2&a,const cfd::fem::Node2&b,const cfd::fem::Node2&c,double x,double y,double&w0,double&w1,double&w2){const double det=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(std::abs(det)<1e-30)return false;w0=((b.y-c.y)*(x-c.x)+(c.x-b.x)*(y-c.y))/det;w1=((c.y-a.y)*(x-c.x)+(a.x-c.x)*(y-c.y))/det;w2=1.0-w0-w1;constexpr double eps=-1e-12;return w0>=eps&&w1>=eps&&w2>=eps;}
}
std::vector<double> fem_nodes_to_fvm_cells(const cfd::fem::Mesh2D& m,std::span<const double> v,const cfd::fvm::PolyMesh&t){m.validate();if(v.size()!=m.node_count())throw std::invalid_argument("FEM projection size mismatch");std::vector<double> out(t.cell_count());for(std::size_t ci=0;ci<t.cell_count();++ci){const auto p=t.cells()[ci].center;bool found=false;for(const auto&tri:m.triangles){double a,b,c;if(!barycentric(m.nodes[tri.node[0]],m.nodes[tri.node[1]],m.nodes[tri.node[2]],p.x,p.y,a,b,c))continue;out[ci]=a*v[tri.node[0]]+b*v[tri.node[1]]+c*v[tri.node[2]];found=true;break;}if(!found)throw std::out_of_range("FVM cell center lies outside FEM mesh projection domain");}return out;}
std::vector<double> fvm_cells_to_fem_nodes(const cfd::fvm::PolyMesh& m,std::span<const double> v,const cfd::fem::Mesh2D&t,std::size_t neighbours){if(v.size()!=m.cell_count()||neighbours==0)throw std::invalid_argument("FVM projection input mismatch");std::vector<double> out(t.node_count());std::vector<std::pair<double,std::size_t>> dist;dist.reserve(m.cell_count());for(std::size_t ni=0;ni<t.node_count();++ni){dist.clear();const auto n=t.nodes[ni];for(std::size_t c=0;c<m.cell_count();++c){const auto d=m.cells()[c].center;const double d2=(d.x-n.x)*(d.x-n.x)+(d.y-n.y)*(d.y-n.y)+d.z*d.z;dist.push_back({d2,c});}const std::size_t k=std::min(neighbours,dist.size());std::nth_element(dist.begin(),dist.begin()+static_cast<std::ptrdiff_t>(k-1),dist.end());double sum=0,wsum=0;if(dist[0].first<1e-28){auto best=*std::min_element(dist.begin(),dist.end());out[ni]=v[best.second];continue;}for(std::size_t j=0;j<k;++j){const double w=1.0/std::max(dist[j].first,1e-28);sum+=w*v[dist[j].second];wsum+=w;}out[ni]=sum/wsum;}return out;}
void StructuredScalarGrid3D::validate() const {if(nx<2||ny<2||nz<2||!(lx>0)||!(ly>0)||!(lz>0)||values.size()!=nx*ny*nz)throw std::invalid_argument("invalid structured scalar grid");}
double StructuredScalarGrid3D::sample(double x,double y,double z) const {validate();x=std::clamp(x,0.0,lx);y=std::clamp(y,0.0,ly);z=std::clamp(z,0.0,lz);const double gx=x/lx*(nx-1),gy=y/ly*(ny-1),gz=z/lz*(nz-1);const auto i0=std::min(static_cast<std::size_t>(gx),nx-2),j0=std::min(static_cast<std::size_t>(gy),ny-2),k0=std::min(static_cast<std::size_t>(gz),nz-2);const double fx=gx-i0,fy=gy-j0,fz=gz-k0;auto at=[&](std::size_t i,std::size_t j,std::size_t k){return values[(k*ny+j)*nx+i];};double sum=0;for(int dk=0;dk<2;++dk)for(int dj=0;dj<2;++dj)for(int di=0;di<2;++di){const double wx=di?fx:1-fx,wy=dj?fy:1-fy,wz=dk?fz:1-fz;sum+=wx*wy*wz*at(i0+di,j0+dj,k0+dk);}return sum;}
std::vector<double> structured_to_fvm_cells(const StructuredScalarGrid3D&s,const cfd::fvm::PolyMesh&t){s.validate();std::vector<double> out(t.cell_count());for(std::size_t i=0;i<t.cell_count();++i){const auto p=t.cells()[i].center;out[i]=s.sample(p.x,p.y,p.z);}return out;}
std::vector<double> structured_to_fem_nodes(const StructuredScalarGrid3D&s,const cfd::fem::Mesh2D&t,double z){s.validate();std::vector<double> out(t.node_count());for(std::size_t i=0;i<t.node_count();++i)out[i]=s.sample(t.nodes[i].x,t.nodes[i].y,z);return out;}
} // namespace cfd::multiphysics
