#include "cfd/solvers/fvm/thermal_transport.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace cfd::fvm {
ThermalTransport::ThermalTransport(PolyMesh mesh,ThermalTransportConfig c):mesh_(std::move(mesh)),config_(c),temperature_(mesh_.cell_count()),next_(mesh_.cell_count()),mass_flux_(mesh_.face_count()),boundary_(mesh_.patches().size()){if(!(c.dt>0)||!(c.density>0)||!(c.default_heat_capacity>0)||!(c.default_conductivity>=0))throw std::invalid_argument("invalid thermal transport controls");cp_=[=](Vec3,double){return c.default_heat_capacity;};k_=[=](Vec3,double){return c.default_conductivity;};}
void ThermalTransport::initialize(double t){std::fill(temperature_.begin(),temperature_.end(),t);time_=0;}void ThermalTransport::initialize(const std::function<double(Vec3)>&f){for(std::size_t i=0;i<temperature_.size();++i)temperature_[i]=f(mesh_.cells()[i].center);time_=0;}
void ThermalTransport::set_boundary(std::string_view p,ThermalBoundary b){boundary_[mesh_.patch_index(p)]=b;}void ThermalTransport::set_face_mass_flux(std::vector<double> f){if(f.size()!=mesh_.face_count())throw std::invalid_argument("thermal face flux size");mass_flux_=std::move(f);}
void ThermalTransport::step(){const double tn=time_+config_.dt;for(std::size_t c=0;c<mesh_.cell_count();++c){const auto x=mesh_.cells()[c].center;const double cp=cp_(x,temperature_[c]),kcell=k_(x,temperature_[c]);if(!(cp>0)||!(kcell>=0)||!std::isfinite(cp)||!std::isfinite(kcell))throw std::runtime_error("invalid temperature-dependent material property");double rate=(source_?source_(x,tn,temperature_[c]):0.0)*mesh_.cells()[c].volume;for(auto fi:mesh_.cell_faces()[c]){const auto&f=mesh_.faces()[fi];const double orient=f.owner==c?1.0:-1.0;double tf=temperature_[c];double cond=0;double cpf=cp;if(!f.boundary()){const auto o=f.owner==c?f.neighbour:f.owner;const double ko=k_(mesh_.cells()[o].center,temperature_[o]);const double kf=2*kcell*ko/std::max(kcell+ko,1e-30);const double d=magnitude(mesh_.cells()[o].center-x);cond=kf*magnitude(f.area)*(temperature_[o]-temperature_[c])/d;const double ph=orient*mass_flux_[fi];tf=ph>=0?temperature_[c]:temperature_[o];cpf=ph>=0?cp:cp_(mesh_.cells()[o].center,temperature_[o]);rate+=cond-ph*cpf*tf;}else{const auto&bc=boundary_[f.patch];if(bc.fixed_temperature){const double d=magnitude(f.center-x);cond=kcell*magnitude(f.area)*(bc.temperature-temperature_[c])/d;rate+=cond;}const double ph=orient*mass_flux_[fi];if(ph>0)rate-=ph*cp*temperature_[c];else if(ph<0&&bc.fixed_temperature)rate-=ph*cp*bc.temperature;}}
        next_[c]=temperature_[c]+config_.dt*rate/(config_.density*cp*mesh_.cells()[c].volume);if(!std::isfinite(next_[c]))throw std::runtime_error("thermal transport diverged");}temperature_.swap(next_);time_=tn;}
void ThermalTransport::set_reactive_radiative_source(std::function<double(Vec3,double,double)> chemistry_heat_release,std::shared_ptr<const RadiationSourceModel> radiation,double environment_temperature){if(!radiation)throw std::invalid_argument("radiation source model is required");if(environment_temperature<0.0||!std::isfinite(environment_temperature))throw std::invalid_argument("invalid radiation environment temperature");source_=[chem=std::move(chemistry_heat_release),radiation=std::move(radiation),environment_temperature](Vec3 x,double time,double temperature){const double chemistry=chem?chem(x,time,temperature):0.0;const double radiative=radiation->volumetric_source(temperature,environment_temperature);if(!std::isfinite(chemistry)||!std::isfinite(radiative))throw std::runtime_error("non-finite reactive-radiative energy source");return chemistry+radiative;};}
void ThermalTransport::set_material(std::function<double(Vec3,double)> heat_capacity,std::function<double(Vec3,double)> conductivity){if(!heat_capacity||!conductivity)throw std::invalid_argument("thermal material callbacks must be non-empty");cp_=std::move(heat_capacity);k_=std::move(conductivity);}
void ThermalTransport::run(std::size_t n){for(std::size_t i=0;i<n;++i)step();}
double ThermalTransport::total_sensible_enthalpy()const{double h=0;for(std::size_t c=0;c<mesh_.cell_count();++c)h+=config_.density*cp_(mesh_.cells()[c].center,temperature_[c])*temperature_[c]*mesh_.cells()[c].volume;return h;}
std::vector<Vec3> boussinesq_acceleration(const PolyMesh& mesh,std::span<const double>T,double tref,double beta,Vec3 g){if(T.size()!=mesh.cell_count()||!std::isfinite(tref)||!std::isfinite(beta))throw std::invalid_argument("invalid Boussinesq field");std::vector<Vec3>a(T.size());for(std::size_t c=0;c<T.size();++c)a[c]=g*(-beta*(T[c]-tref));return a;}
} // namespace cfd::fvm
