#pragma once

#include "cfd/core/device_residency.hpp"
#include "cfd/multibody/math.hpp"

#if defined(CFD_HAS_SYCL)
#include <sycl/sycl.hpp>

#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

namespace cfd::multibody {

inline constexpr std::uint64_t invalid_dem_global_id = ~std::uint64_t{0};

struct ResidentDemParticle {
    std::uint64_t global_id{invalid_dem_global_id};
    int owner_rank{};
    Vec3 position{};
    Vec3 linear_velocity{};
    Vec3 angular_velocity{};
    double radius{0.5};
    double mass{1.0};
};

struct ResidentDemSyclConfig {
    std::size_t capacity{1024U};
    Vec3 domain_min{-1.0,-1.0,-1.0};
    Vec3 domain_max{ 1.0, 1.0, 1.0};
    double cell_size{0.1};
    double dt{1.0e-4};
    Vec3 gravity{0.0,-9.81,0.0};
    double normal_stiffness{1.0e5};
    double normal_damping{20.0};
    double tangential_stiffness{5.0e4};
    double tangential_damping{20.0};
    double friction{0.5};
    double rolling_resistance{0.01};
    double cohesion_force{};
    std::size_t history_slots_per_particle{24U};
};

struct ResidentDemDeviceView {
    std::size_t count{};
    std::uint64_t* global_id{};
    std::int32_t* owner_rank{};
    float* x{}; float* y{}; float* z{};
    float* vx{}; float* vy{}; float* vz{};
    float* wx{}; float* wy{}; float* wz{};
    float* radius{}; float* inverse_mass{};
    float* fx{}; float* fy{}; float* fz{};
    float* tx{}; float* ty{}; float* tz{};
};

// Compact POD payload used by GPU-aware distributed exchange. Single precision
// matches the resident DEM hot state; global IDs remain 64-bit and stable.
struct ResidentDemPackedParticle {
    std::uint64_t global_id{invalid_dem_global_id};
    std::int32_t owner_rank{};
    float x{},y{},z{};
    float vx{},vy{},vz{};
    float wx{},wy{},wz{};
    float radius{};
    float inverse_mass{};
    float inverse_inertia{};
};

// One fixed slot per resident particle history slot. Packing a fixed number of
// slots avoids host-side variable-length metadata construction and preserves
// Mindlin history across device-side migration/reordering.
struct ResidentDemPackedHistory {
    std::uint64_t owner_global_id{invalid_dem_global_id};
    std::uint64_t neighbor_global_id{invalid_dem_global_id};
    float tx{},ty{},tz{};
};

// Equal-and-opposite force/torque record generated by a local<->ghost contact
// or cross-rank bond.  Records remain compact and trivially copyable so they
// can be reverse-exchanged directly from device USM on GPU-aware MPI stacks.
struct ResidentDemPackedForce {
    std::uint64_t global_id{invalid_dem_global_id};
    std::int32_t owner_rank{};
    float fx{},fy{},fz{};
    float tx{},ty{},tz{};
};

// Device-resident bonded-particle state. Pair IDs are canonicalized (a<b),
// therefore the rank owning particle_a is the unique bond/history owner.
struct ResidentDemPackedBond {
    std::uint64_t particle_a{invalid_dem_global_id};
    std::uint64_t particle_b{invalid_dem_global_id};
    float rest_length{};
    float normal_stiffness{1.0e5F};
    float shear_stiffness{5.0e4F};
    float normal_damping{50.0F};
    float shear_damping{25.0F};
    float tensile_failure_force{1.0e3F};
    float shear_failure_force{1.0e3F};
    float damage_onset_ratio{0.7F};
    float tangential_x{},tangential_y{},tangential_z{};
    float damage{};
    std::uint32_t broken{};
};

struct ResidentDemExchangeDeviceView {
    std::size_t count{};
    std::size_t capacity{};
    std::size_t history_slots_per_particle{};
    std::uint64_t* global_id{};
    std::int32_t* owner_rank{};
    float *x{},*y{},*z{},*vx{},*vy{},*vz{},*wx{},*wy{},*wz{};
    float *radius{},*inverse_mass{},*inverse_inertia{};
    std::uint64_t* history_neighbor{};
    std::uint32_t* history_seen{};
    float *history_tx{},*history_ty{},*history_tz{};
};

// Device-resident spherical DEM baseline. The ordinary step path performs no
// bulk host transfer: grid construction, neighbor bucketing, persistent
// Mindlin history, pair forces, rolling torque and integration all run on the
// supplied SYCL queue. Host traffic is restricted to explicit upload/download
// and scalar diagnostics.
class ResidentDemSycl {
public:
    ResidentDemSycl(sycl::queue& queue, ResidentDemSyclConfig config);
    ~ResidentDemSycl() noexcept;
    ResidentDemSycl(const ResidentDemSycl&) = delete;
    ResidentDemSycl& operator=(const ResidentDemSycl&) = delete;

    void upload(std::span<const ResidentDemParticle> particles);
    [[nodiscard]] std::vector<ResidentDemParticle> download() const;
    void build_neighbor_buckets();
    void step(std::size_t steps = 1U);

    // Split-step distributed contact API. begin_distributed_contact_step()
    // initializes one ordinary DEM timestep and advances the persistent contact
    // stamp exactly once.  Interior owned-owned contacts may then execute while
    // halo communication is in flight. Boundary owned-owned and local-ghost
    // contacts share the same force arrays/history stamp before finish integrates.
    void begin_distributed_contact_step();
    void apply_owned_contacts_interior_device(const std::uint8_t* boundary_mask);
    void apply_owned_contacts_boundary_device(const std::uint8_t* boundary_mask);
    void apply_ghost_contacts_device(
        const ResidentDemPackedParticle* device_ghosts,
        std::size_t ghost_count,
        const std::uint8_t* boundary_mask,
        int local_rank,
        ResidentDemPackedForce* device_remote_forces,
        std::uint32_t* shared_remote_force_count,
        std::size_t remote_force_capacity);
    void apply_bonds_device(
        ResidentDemPackedBond* device_bonds,
        std::size_t bond_count,
        const ResidentDemPackedParticle* device_ghosts,
        std::size_t ghost_count,
        int local_rank,
        ResidentDemPackedForce* device_remote_forces,
        std::uint32_t* shared_remote_force_count,
        std::size_t remote_force_capacity);
    void apply_remote_forces_device(const ResidentDemPackedForce* device_forces,std::size_t force_count);
    void finish_distributed_contact_step();

    // GPU-aware transport primitives. The index pointer and packed payload
    // pointers must be USM pointers in the same SYCL context as this solver.
    // Packing/restoration includes the fixed-size Mindlin history table.
    void pack_indices_device(
        const std::uint32_t* device_indices,
        std::size_t index_count,
        ResidentDemPackedParticle* device_particles,
        ResidentDemPackedHistory* device_history) const;
    void append_packed_device(
        const ResidentDemPackedParticle* device_particles,
        const ResidentDemPackedHistory* device_history,
        std::size_t packed_count,
        int owner_rank_override = -1);
    // Keep only particles whose centers lie in [x_min,x_max). This is the
    // device-side compaction used after outgoing slab migrants have been packed.
    // It performs only a scalar synchronization to publish the new resident count.
    void retain_x_slab_device(double x_min,double x_max,int owner_rank);

    [[nodiscard]] double total_kinetic_energy() const;
    [[nodiscard]] std::size_t particle_count() const noexcept { return count_; }
    [[nodiscard]] std::size_t capacity() const noexcept { return config_.capacity; }
    [[nodiscard]] std::size_t history_slots_per_particle() const noexcept { return config_.history_slots_per_particle; }
    [[nodiscard]] std::size_t cell_count() const noexcept { return cell_count_; }
    [[nodiscard]] std::size_t resident_bytes() const noexcept;
    [[nodiscard]] ResidentDemDeviceView device_view() noexcept;
    [[nodiscard]] ResidentDemExchangeDeviceView exchange_device_view() noexcept;
    [[nodiscard]] sycl::queue& queue() noexcept { return queue_; }
    [[nodiscard]] const cfd::core::DeviceTransferStats& transfer_stats() const noexcept { return transfer_stats_; }
    void reset_transfer_stats() const noexcept { transfer_stats_.reset(); }

private:
    sycl::queue& queue_;
    ResidentDemSyclConfig config_{};
    std::size_t count_{};
    std::size_t nx_{},ny_{},nz_{},cell_count_{};
    std::uint32_t history_stamp_{1U};

    std::uint64_t* global_id_{};
    std::int32_t* owner_rank_{};
    float *x_{},*y_{},*z_{},*vx_{},*vy_{},*vz_{},*wx_{},*wy_{},*wz_{};
    float *radius_{},*inverse_mass_{},*inverse_inertia_{};
    float *fx_{},*fy_{},*fz_{},*tx_{},*ty_{},*tz_{};
    std::uint32_t *particle_cell_{},*cell_counts_{},*cell_offsets_{},*cell_cursor_{},*sorted_indices_{};
    std::uint64_t* history_neighbor_{};
    std::uint32_t* history_seen_{};
    float *history_tx_{},*history_ty_{},*history_tz_{};
    mutable float* reduction_scalar_{};
    mutable std::uint32_t* compaction_count_{};
    mutable cfd::core::DeviceTransferStats transfer_stats_{};

    void clear_forces_with_gravity();
    void apply_contacts();
    void apply_contacts_partition(const std::uint8_t* boundary_mask,int partition_mode);
    void integrate();
    void cleanup_history(std::uint32_t stamp);
    void allocate();
    void release() noexcept;
};

} // namespace cfd::multibody
#endif
