#include "cfd/optics/nonsequential.hpp"
#include <cmath>
#include <algorithm>
#include <limits>
#include <stdexcept>
namespace cfd::optics {
void NonSequentialScene::add_plane(NsPlane p){p.normal=normalized(p.normal);if(p.reflectance<0||p.transmittance<0||p.absorptance<0||p.scatter_fraction<0||p.reflectance+p.transmittance+p.absorptance+p.scatter_fraction>1.0000001||!(p.refractive_index_before>0)||!(p.refractive_index_after>0))throw std::invalid_argument("invalid non-sequential plane");planes_.push_back(p);}
std::vector<NsRay> NonSequentialScene::trace(NsRay seed,std::size_t maxb,double minp)const{std::vector<NsRay>active{seed},finished;for(std::size_t depth=0;depth<maxb&&!active.empty();++depth){std::vector<NsRay>next;for(auto r:active){double best=std::numeric_limits<double>::infinity();const NsPlane* hit=nullptr;for(const auto&p:planes_){const double den=dot(r.ray.direction,p.normal);if(std::abs(den)<1e-12)continue;const Vec3 d{p.point.x-r.ray.origin.x,p.point.y-r.ray.origin.y,p.point.z-r.ray.origin.z};const double t=dot(d,p.normal)/den;if(t>1e-9&&t<best){best=t;hit=&p;}}if(!hit){finished.push_back(r);continue;}const Vec3 point{r.ray.origin.x+best*r.ray.direction.x,r.ray.origin.y+best*r.ray.direction.y,r.ray.origin.z+best*r.ray.direction.z};if(hit->reflectance>0&&r.power*hit->reflectance>=minp){NsRay q=r;q.ray.origin=point;q.ray.direction=reflect(r.ray.direction,hit->normal);q.power*=hit->reflectance;++q.bounces;next.push_back(q);}if(hit->transmittance>0&&r.power*hit->transmittance>=minp){auto tdir=refract(r.ray.direction,hit->normal,hit->refractive_index_before,hit->refractive_index_after);if(tdir){NsRay q=r;q.ray.origin=point;q.ray.direction=*tdir;q.power*=hit->transmittance;++q.bounces;next.push_back(q);}}if(hit->scatter_fraction>0&&r.power*hit->scatter_fraction>=minp){NsRay q=r;q.ray.origin=point;const double side=dot(r.ray.direction,hit->normal)<0?-1.0:1.0;q.ray.direction=normalized({hit->normal.x*side+0.35,hit->normal.y+0.17,hit->normal.z*side});q.power*=hit->scatter_fraction;++q.bounces;next.push_back(q);}}active.swap(next);}finished.insert(finished.end(),active.begin(),active.end());return finished;}

StrayLightSummary summarize_stray_light(std::span<const NsRay> rays,double launched_power){if(!(launched_power>=0.0))throw std::invalid_argument("invalid launched optical power");StrayLightSummary s;for(const auto&r:rays){s.total_power+=r.power;if(r.bounces>0)s.reflected_power+=r.power;else s.transmitted_power+=r.power;}s.absorbed_power=std::max(0.0,launched_power-s.total_power);return s;}
std::vector<GhostPath> rank_ghost_paths(std::span<const NsRay> rays,std::size_t minimum_bounces){std::vector<GhostPath> out;for(const auto&r:rays)if(r.bounces>=minimum_bounces)out.push_back({r.bounces,r.power,r.ray});std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.power>b.power;});return out;}

} // namespace cfd::optics
