#include "cfd/solvers/fem/brinkman2d.hpp"
#include "cfd/core/csr_matrix.hpp"
#include "cfd/core/iterative_solvers.hpp"
#include <array>
#include <cmath>
#include <stdexcept>
namespace cfd::fem { namespace {struct G{double area;std::array<std::array<double,2>,3>grad;Node2 c;};G geom(const Mesh2D&m,const Tri3&t){const auto&a=m.nodes[t.node[0]],&b=m.nodes[t.node[1]],&c=m.nodes[t.node[2]];const double det=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),A=.5*std::abs(det),inv=1.0/det;return {A,{{{(b.y-c.y)*inv,(c.x-b.x)*inv},{(c.y-a.y)*inv,(a.x-c.x)*inv},{(a.y-b.y)*inv,(b.x-a.x)*inv}}},{(a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3}};}}
Brinkman2D::Brinkman2D(Mesh2D m,Brinkman2DConfig c):mesh_(std::move(m)),c_(c),velocity_(mesh_.node_count()){mesh_.validate();if(!(c.viscosity>0)||!(c.effective_viscosity>0)||!(c.permeability>0))throw std::invalid_argument("invalid Brinkman controls");}
void Brinkman2D::solve(const std::function<Displacement2(Node2)>& force){if(!force)throw std::invalid_argument("Brinkman body force required");const auto n=mesh_.node_count();std::vector<std::size_t>map(n,static_cast<std::size_t>(-1));std::size_t nf=0;for(std::size_t i=0;i<n;++i)if(!(zero_boundary_&&mesh_.boundary_node[i]))map[i]=nf++;cfd::core::CsrBuilder b(nf,nf);std::vector<double>rx(nf),ry(nf);const double drag=c_.viscosity/c_.permeability;for(const auto&t:mesh_.triangles){auto g=geom(mesh_,t);auto f=force(g.c);for(std::size_t i=0;i<3;++i){auto gi=t.node[i];if(map[gi]==static_cast<std::size_t>(-1))continue;auto row=map[gi];rx[row]+=f.x*g.area/3;ry[row]+=f.y*g.area/3;for(std::size_t j=0;j<3;++j){auto gj=t.node[j];if(map[gj]==static_cast<std::size_t>(-1))continue;double kij=c_.effective_viscosity*g.area*(g.grad[i][0]*g.grad[j][0]+g.grad[i][1]*g.grad[j][1])+drag*g.area*(i==j?2.0:1.0)/12.0;b.add(row,map[gj],kij);}}}auto A=b.build();cfd::core::JacobiPreconditioner jac(A.diagonal());cfd::core::KrylovWorkspace ws;std::vector<double>x(nf),y(nf);auto solve=[&](const std::vector<double>&r,std::vector<double>&u){auto q=cfd::core::preconditioned_conjugate_gradient(r,u,[&](auto in,auto out){A.multiply(in,out);},[&](auto in,auto out){jac(in,out);},ws,c_.max_iterations,c_.tolerance);if(!q.converged)throw std::runtime_error("Brinkman solve failed");};solve(rx,x);solve(ry,y);for(std::size_t i=0;i<n;++i)if(map[i]!=static_cast<std::size_t>(-1))velocity_[i]={x[map[i]],y[map[i]]};}
} // namespace cfd::fem
