#include "cfd/solvers/fem/dynamic_bar1d.hpp"
#include <cmath>
#include <stdexcept>
namespace cfd::fem {
DynamicBar1D::DynamicBar1D(DynamicBar1DConfig c):c_(c),u_(c.elements),v_(c.elements),a_(c.elements),rhs_(c.elements),candidate_(c.elements){if(c.elements<2||!(c.length>0)||!(c.area>0)||!(c.young_modulus>0)||!(c.density>0)||!(c.dt>0)||!(c.newmark_beta>0)||!(c.newmark_gamma>0))throw std::invalid_argument("invalid dynamic bar controls");build_matrices();}
void DynamicBar1D::build_matrices(){const std::size_t n=c_.elements;const double h=c_.length/static_cast<double>(c_.elements),ke=c_.young_modulus*c_.area/h,me=c_.density*c_.area*h/6.0;cfd::core::CsrBuilder kb(n,n),mb(n,n),ab(n,n);for(std::size_t e=0;e<c_.elements;++e){const std::size_t g[2]{e,e+1};const double kk[2][2]{{ke,-ke},{-ke,ke}},mm[2][2]{{2*me,me},{me,2*me}};for(int i=0;i<2;++i){if(g[i]==0)continue;for(int j=0;j<2;++j){if(g[j]==0)continue;const auto r=g[i]-1,co=g[j]-1;kb.add(r,co,kk[i][j]);mb.add(r,co,mm[i][j]);ab.add(r,co,mm[i][j]+c_.newmark_beta*c_.dt*c_.dt*kk[i][j]);}}}k_=kb.build();m_=mb.build();effective_=ab.build();}
void DynamicBar1D::initialize(const std::function<double(double)>&d,const std::function<double(double)>&vel){if(!d)throw std::invalid_argument("dynamic bar displacement initializer required");for(std::size_t i=0;i<c_.elements;++i){const double x=c_.length*static_cast<double>(i+1)/static_cast<double>(c_.elements);u_[i]=d(x);v_[i]=vel?vel(x):0.0;}std::vector<double>ku(c_.elements),neg(c_.elements);k_.multiply(u_,ku);for(std::size_t i=0;i<neg.size();++i)neg[i]=-ku[i];candidate_.assign(c_.elements,0.0);cfd::core::JacobiPreconditioner jac(m_.diagonal());cfd::core::KrylovWorkspace ws;auto res=cfd::core::preconditioned_conjugate_gradient(neg,candidate_,[&](auto x,auto y){m_.multiply(x,y);},[&](auto x,auto y){jac(x,y);},ws,c_.linear_iterations,c_.linear_tolerance);if(!res.converged)throw std::runtime_error("dynamic bar initial acceleration solve failed");a_=candidate_;time_=0;}
void DynamicBar1D::step(double tip_force){const double dt=c_.dt,b=c_.newmark_beta,g=c_.newmark_gamma;std::vector<double>up(u_.size()),vp(v_.size()),kup(u_.size());for(std::size_t i=0;i<u_.size();++i){up[i]=u_[i]+dt*v_[i]+dt*dt*(0.5-b)*a_[i];vp[i]=v_[i]+dt*(1-g)*a_[i];}k_.multiply(up,kup);for(std::size_t i=0;i<rhs_.size();++i)rhs_[i]=-kup[i];rhs_.back()+=tip_force;candidate_=a_;cfd::core::JacobiPreconditioner jac(effective_.diagonal());cfd::core::KrylovWorkspace ws;auto res=cfd::core::preconditioned_conjugate_gradient(rhs_,candidate_,[&](auto x,auto y){effective_.multiply(x,y);},[&](auto x,auto y){jac(x,y);},ws,c_.linear_iterations,c_.linear_tolerance);if(!res.converged)throw std::runtime_error("dynamic bar Newmark solve failed");a_=candidate_;for(std::size_t i=0;i<u_.size();++i){u_[i]=up[i]+b*dt*dt*a_[i];v_[i]=vp[i]+g*dt*a_[i];}time_+=dt;}
void DynamicBar1D::run(std::size_t n,double f){for(std::size_t i=0;i<n;++i)step(f);}double DynamicBar1D::kinetic_energy()const{std::vector<double>mv(v_.size());m_.multiply(v_,mv);double e=0;for(std::size_t i=0;i<v_.size();++i)e+=.5*v_[i]*mv[i];return e;}double DynamicBar1D::strain_energy()const{std::vector<double>ku(u_.size());k_.multiply(u_,ku);double e=0;for(std::size_t i=0;i<u_.size();++i)e+=.5*u_[i]*ku[i];return e;}
} // namespace cfd::fem
