#include "cfd/solvers/fem/eddy_current2d.hpp"
#include "cfd/core/csr_matrix.hpp"
#include <array>
#include <cmath>
#include <numbers>
#include <stdexcept>
namespace cfd::fem {namespace {struct G{double area;std::array<std::array<double,2>,3>grad;Node2 c;};G geom(const Mesh2D&m,const Tri3&t){auto a=m.nodes[t.node[0]],b=m.nodes[t.node[1]],c=m.nodes[t.node[2]];double det=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);double area=.5*std::abs(det);if(!(area>0))throw std::runtime_error("degenerate eddy-current triangle");double inv=1.0/det;return {area,{{{(b.y-c.y)*inv,(c.x-b.x)*inv},{(c.y-a.y)*inv,(a.x-c.x)*inv},{(a.y-b.y)*inv,(b.x-a.x)*inv}}},{(a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3}};}}
EddyCurrent2D::EddyCurrent2D(Mesh2D m,EddyCurrent2DConfig c):mesh_(std::move(m)),config_(c),a_(mesh_.node_count()){mesh_.validate();if(c.frequency_hz<0||c.max_iterations==0||c.gmres_restart==0||!(c.relative_tolerance>0))throw std::invalid_argument("invalid eddy-current controls");}
void EddyCurrent2D::solve(const std::function<double(Node2)>&nu,const std::function<double(Node2)>&sigma,const std::function<std::complex<double>(Node2)>&J){if(!nu||!sigma||!J)throw std::invalid_argument("eddy-current fields required");std::vector<std::size_t>map(mesh_.node_count(),static_cast<std::size_t>(-1));std::size_t nf=0;for(std::size_t n=0;n<mesh_.node_count();++n)if(!mesh_.boundary_node[n])map[n]=nf++;if(nf==0)throw std::runtime_error("no eddy-current free nodes");cfd::core::CsrBuilder b(2*nf,2*nf);std::vector<double>rhs(2*nf);double omega=2*std::numbers::pi*config_.frequency_hz;for(auto t:mesh_.triangles){auto g=geom(mesh_,t);double rel=nu(g.c),cond=sigma(g.c);auto src=J(g.c);if(!(rel>0)||cond<0)throw std::invalid_argument("invalid eddy-current material");for(std::size_t i=0;i<3;++i){auto ni=t.node[i];if(mesh_.boundary_node[ni])continue;auto ri=map[ni];rhs[ri]+=src.real()*g.area/3;rhs[nf+ri]+=src.imag()*g.area/3;for(std::size_t j=0;j<3;++j){auto nj=t.node[j];if(mesh_.boundary_node[nj])continue;auto cj=map[nj];double k=rel*g.area*(g.grad[i][0]*g.grad[j][0]+g.grad[i][1]*g.grad[j][1]);double mass=cond*g.area*(i==j?2.0:1.0)/12.0;b.add(ri,cj,k);b.add(ri,nf+cj,-omega*mass);b.add(nf+ri,cj,omega*mass);b.add(nf+ri,nf+cj,k);}}}auto A=b.build();cfd::core::Ilu0Preconditioner ilu(A);std::vector<double>x(2*nf);result_=cfd::core::restarted_gmres(rhs,x,[&](std::span<const double>v,std::span<double>o){A.multiply(v,o);},[&](std::span<const double>r,std::span<double>z){ilu(r,z);},config_.max_iterations,config_.gmres_restart,config_.relative_tolerance);if(!result_.converged)throw std::runtime_error("eddy-current GMRES failed");std::fill(a_.begin(),a_.end(),std::complex<double>{});for(std::size_t n=0;n<mesh_.node_count();++n)if(!mesh_.boundary_node[n])a_[n]={x[map[n]],x[nf+map[n]]};}
}
