#include "cfd/solvers/lbm/visualization.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <stdexcept>
namespace cfd::lbm {namespace {std::size_t id(std::size_t x,std::size_t y,std::size_t nx){return y*nx+x;}Vector2 sample(std::size_t nx,std::size_t ny,std::span<const Vector2>u,Vector2 p){if(p.x<0||p.y<0||p.x>static_cast<double>(nx-1)||p.y>static_cast<double>(ny-1))return {};auto x=static_cast<std::size_t>(std::clamp(p.x,0.0,static_cast<double>(nx-1))),y=static_cast<std::size_t>(std::clamp(p.y,0.0,static_cast<double>(ny-1)));return u[id(x,y,nx)];}}
void write_vtk_structured_2d(const std::filesystem::path&p,std::size_t nx,std::size_t ny,std::span<const double>s,std::span<const Vector2>u,const char*name){if(nx*ny!=s.size()||(!u.empty()&&u.size()!=s.size()))throw std::invalid_argument("LBM VTK field size mismatch");std::ofstream o(p);if(!o)throw std::runtime_error("cannot create LBM VTK");o<<"# vtk DataFile Version 3.0\ncfd_solvers LBM\nASCII\nDATASET STRUCTURED_POINTS\nDIMENSIONS "<<nx<<' '<<ny<<" 1\nORIGIN 0 0 0\nSPACING 1 1 1\nPOINT_DATA "<<s.size()<<"\nSCALARS "<<name<<" double 1\nLOOKUP_TABLE default\n"<<std::setprecision(17);for(double v:s)o<<v<<'\n';if(!u.empty()){o<<"VECTORS velocity double\n";for(auto v:u)o<<v.x<<' '<<v.y<<" 0\n";}}
std::vector<double> vorticity_2d(std::size_t nx,std::size_t ny,std::span<const Vector2>u,double dx,double dy){if(nx<3||ny<3||u.size()!=nx*ny||!(dx>0)||!(dy>0))throw std::invalid_argument("invalid LBM vorticity grid");std::vector<double>w(nx*ny);for(std::size_t y=1;y+1<ny;++y)for(std::size_t x=1;x+1<nx;++x){double dvdx=(u[id(x+1,y,nx)].y-u[id(x-1,y,nx)].y)/(2*dx),dudy=(u[id(x,y+1,nx)].x-u[id(x,y-1,nx)].x)/(2*dy);w[id(x,y,nx)]=dvdx-dudy;}return w;}
std::vector<double> horizontal_slice(std::size_t nx,std::size_t ny,std::span<const double>f,std::size_t y){if(f.size()!=nx*ny||y>=ny)throw std::invalid_argument("invalid LBM slice");return {f.begin()+static_cast<std::ptrdiff_t>(y*nx),f.begin()+static_cast<std::ptrdiff_t>((y+1)*nx)};}
std::vector<Vector2> streamline_2d(std::size_t nx,std::size_t ny,std::span<const Vector2>u,Vector2 p,double h,std::size_t max){if(u.size()!=nx*ny||!(h>0)||max==0)throw std::invalid_argument("invalid streamline controls");std::vector<Vector2>out;for(std::size_t i=0;i<max;++i){if(p.x<0||p.y<0||p.x>=static_cast<double>(nx)||p.y>=static_cast<double>(ny))break;out.push_back(p);auto v=sample(nx,ny,u,p);double m=std::hypot(v.x,v.y);if(m<1e-14)break;p.x+=h*v.x/m;p.y+=h*v.y/m;}return out;}
void write_pgm_scalar(const std::filesystem::path&p,std::size_t nx,std::size_t ny,std::span<const double>f){if(f.size()!=nx*ny||f.empty())throw std::invalid_argument("invalid PGM field");auto [mn,mx]=std::minmax_element(f.begin(),f.end());double span=*mx-*mn;std::ofstream o(p);if(!o)throw std::runtime_error("cannot create PGM");o<<"P2\n"<<nx<<' '<<ny<<"\n255\n";for(double v:f){int q=span>0?static_cast<int>(std::lround(255.0*(v-*mn)/span)):0;o<<std::clamp(q,0,255)<<' ';}}
} // namespace cfd::lbm
