#include "cfd/core/geometric_multigrid.hpp"
#include <cmath>
#include <span>
#include <stdexcept>
namespace cfd::core {namespace {std::size_t id(std::size_t i,std::size_t j,std::size_t n){return j*n+i;}}
PoissonMultigrid2D::PoissonMultigrid2D(std::size_t n):n_(n){if(n<3||((n+1)&n)!=0)throw std::invalid_argument("multigrid interior size must be 2^k-1");}
void PoissonMultigrid2D::smooth(std::size_t n,const std::vector<double>&f,std::vector<double>&u,int sweeps){const double h=1.0/static_cast<double>(n+1),h2=h*h;for(int s=0;s<sweeps;++s)for(int color=0;color<2;++color)for(std::size_t j=0;j<n;++j)for(std::size_t i=0;i<n;++i)if(static_cast<int>((i+j)&1U)==color){double nb=0;if(i)nb+=u[id(i-1,j,n)];if(i+1<n)nb+=u[id(i+1,j,n)];if(j)nb+=u[id(i,j-1,n)];if(j+1<n)nb+=u[id(i,j+1,n)];u[id(i,j,n)]=.25*(h2*f[id(i,j,n)]+nb);}}
void PoissonMultigrid2D::residual(std::size_t n,const std::vector<double>&f,const std::vector<double>&u,std::vector<double>&r){const double h=1.0/static_cast<double>(n+1),invh2=1/(h*h);for(std::size_t j=0;j<n;++j)for(std::size_t i=0;i<n;++i){double nb=0;if(i)nb+=u[id(i-1,j,n)];if(i+1<n)nb+=u[id(i+1,j,n)];if(j)nb+=u[id(i,j-1,n)];if(j+1<n)nb+=u[id(i,j+1,n)];r[id(i,j,n)]=f[id(i,j,n)]-(4*u[id(i,j,n)]-nb)*invh2;}}
void PoissonMultigrid2D::vcycle(std::size_t n,const std::vector<double>&f,std::vector<double>&u){if(n<=3){smooth(n,f,u,20);return;}smooth(n,f,u,3);std::vector<double>r(n*n);residual(n,f,u,r);const std::size_t nc=(n-1)/2;std::vector<double>fc(nc*nc),ec(nc*nc);for(std::size_t J=0;J<nc;++J)for(std::size_t I=0;I<nc;++I){const std::size_t i=2*I+1,j=2*J+1;double v=4*r[id(i,j,n)];v+=2*(r[id(i-1,j,n)]+r[id(i+1,j,n)]+r[id(i,j-1,n)]+r[id(i,j+1,n)]);v+=r[id(i-1,j-1,n)]+r[id(i+1,j-1,n)]+r[id(i-1,j+1,n)]+r[id(i+1,j+1,n)];fc[id(I,J,nc)]=v/16.0;}vcycle(nc,fc,ec);for(std::size_t J=0;J<nc;++J)for(std::size_t I=0;I<nc;++I){const std::size_t i=2*I+1,j=2*J+1;const double e=ec[id(I,J,nc)];u[id(i,j,n)]+=e;if(i>0)u[id(i-1,j,n)]+=.5*e;if(i+1<n)u[id(i+1,j,n)]+=.5*e;if(j>0)u[id(i,j-1,n)]+=.5*e;if(j+1<n)u[id(i,j+1,n)]+=.5*e;}smooth(n,f,u,3);}
MultigridResult PoissonMultigrid2D::solve(std::span<const double>rhs,std::span<double>sol,std::size_t max,double tol)const{if(rhs.size()!=n_*n_||sol.size()!=n_*n_||max==0||!(tol>0))throw std::invalid_argument("invalid multigrid solve inputs");std::vector<double>f(rhs.begin(),rhs.end()),u(sol.begin(),sol.end()),r(n_*n_);double fn=0;for(double x:f)fn+=x*x;fn=std::sqrt(fn);if(fn==0)fn=1;for(std::size_t c=0;c<max;++c){vcycle(n_,f,u);residual(n_,f,u,r);double rn=0;for(double x:r)rn+=x*x;rn=std::sqrt(rn)/fn;if(rn<tol){std::copy(u.begin(),u.end(),sol.begin());return {true,c+1,rn};}}residual(n_,f,u,r);double rn=0;for(double x:r)rn+=x*x;std::copy(u.begin(),u.end(),sol.begin());return {false,max,std::sqrt(rn)/fn};}
} // namespace cfd::core
