#include "cfd/io/mesh_io.hpp"
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <unordered_map>
namespace cfd::io { namespace {
struct GmshRaw {std::vector<cfd::fem::Point3> nodes;std::vector<std::array<std::size_t,3>> tri;std::vector<std::array<std::size_t,4>> tet;};
GmshRaw gmsh(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open Gmsh file");std::string line;std::unordered_map<long,std::size_t> id;GmshRaw r;while(std::getline(in,line)){if(line=="$MeshFormat"){std::getline(in,line);std::istringstream ss(line);double ver;int fmt,sz;ss>>ver>>fmt>>sz;if(ver<2.0||ver>=3.0||fmt!=0)throw std::runtime_error("only ASCII Gmsh v2 is supported");}
else if(line=="$Nodes"){std::getline(in,line);const auto n=static_cast<std::size_t>(std::stoull(line));r.nodes.reserve(n);for(std::size_t i=0;i<n;++i){std::getline(in,line);std::istringstream ss(line);long tag;double x,y,z;ss>>tag>>x>>y>>z;id[tag]=r.nodes.size();r.nodes.push_back({x,y,z});}std::getline(in,line);if(line!="$EndNodes")throw std::runtime_error("malformed Gmsh nodes");}
else if(line=="$Elements"){std::getline(in,line);const auto n=static_cast<std::size_t>(std::stoull(line));for(std::size_t i=0;i<n;++i){std::getline(in,line);std::istringstream ss(line);long eid;int type,nt;ss>>eid>>type>>nt;for(int t=0;t<nt;++t){long skip;ss>>skip;}if(type==2){long a,b,c;ss>>a>>b>>c;r.tri.push_back({id.at(a),id.at(b),id.at(c)});}else if(type==4){long a,b,c,d;ss>>a>>b>>c>>d;r.tet.push_back({id.at(a),id.at(b),id.at(c),id.at(d)});}}std::getline(in,line);if(line!="$EndElements")throw std::runtime_error("malformed Gmsh elements");}}
if(r.nodes.empty())throw std::runtime_error("Gmsh mesh contains no nodes");return r;}
void vtu_header(std::ostream&o,std::size_t points,std::size_t cells){o<<"<?xml version=\"1.0\"?>\n<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n<UnstructuredGrid><Piece NumberOfPoints=\""<<points<<"\" NumberOfCells=\""<<cells<<"\">\n";}
}
cfd::fem::Mesh2D read_gmsh_v2_tri2d(const std::filesystem::path&p){auto r=gmsh(p);if(r.tri.empty())throw std::runtime_error("Gmsh file has no Tri3 elements");cfd::fem::Mesh2D m;m.nodes.reserve(r.nodes.size());for(const auto&n:r.nodes)m.nodes.push_back({n.x,n.y});for(auto t:r.tri)m.triangles.push_back({t});m.boundary_node.assign(m.nodes.size(),0);std::unordered_map<std::uint64_t,int> edge_count;auto key=[](std::size_t a,std::size_t b){if(a>b)std::swap(a,b);return (static_cast<std::uint64_t>(a)<<32)|static_cast<std::uint64_t>(b);};for(const auto&t:m.triangles)for(int e=0;e<3;++e)++edge_count[key(t.node[e],t.node[(e+1)%3])];for(const auto&t:m.triangles)for(int e=0;e<3;++e){auto a=t.node[e],b=t.node[(e+1)%3];if(edge_count[key(a,b)]==1){m.boundary_edges.push_back({{a,b},0});m.boundary_node[a]=m.boundary_node[b]=1;}}m.validate();return m;}
cfd::fem::Mesh3D read_gmsh_v2_tet3d(const std::filesystem::path&p){auto r=gmsh(p);if(r.tet.empty())throw std::runtime_error("Gmsh file has no Tet4 elements");cfd::fem::Mesh3D m;m.nodes=r.nodes;for(auto t:r.tet)m.tetrahedra.push_back({t});m.boundary_node.assign(m.nodes.size(),0);for(const auto&t:m.tetrahedra)for(auto n:t.node)m.boundary_node[n]=1;m.validate();return m;}
TriangleSurface read_obj_triangles(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open OBJ");std::vector<cfd::fem::Point3> v;TriangleSurface s;std::string line;while(std::getline(in,line)){std::istringstream ss(line);std::string op;ss>>op;if(op=="v"){cfd::fem::Point3 q;ss>>q.x>>q.y>>q.z;v.push_back(q);}else if(op=="f"){std::array<std::size_t,3> idx{};for(int i=0;i<3;++i){std::string tok;ss>>tok;auto slash=tok.find('/');long id=std::stol(tok.substr(0,slash));if(id<=0||static_cast<std::size_t>(id)>v.size())throw std::runtime_error("OBJ index out of range");idx[i]=static_cast<std::size_t>(id-1);}s.triangles.push_back({v[idx[0]],v[idx[1]],v[idx[2]]});}}return s;}
TriangleSurface read_ascii_stl(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open STL");TriangleSurface s;std::string w;std::vector<cfd::fem::Point3> v;while(in>>w){if(w=="vertex"){cfd::fem::Point3 q;in>>q.x>>q.y>>q.z;v.push_back(q);if(v.size()==3){s.triangles.push_back({v[0],v[1],v[2]});v.clear();}}}if(!v.empty())throw std::runtime_error("malformed ASCII STL");return s;}
void write_vtu(const std::filesystem::path&p,const cfd::fem::Mesh2D&m,const std::vector<double>& scalar,std::string name){if(!scalar.empty()&&scalar.size()!=m.node_count())throw std::invalid_argument("VTU scalar size mismatch");std::ofstream o(p);if(!o)throw std::runtime_error("cannot create VTU");o<<std::setprecision(17);vtu_header(o,m.node_count(),m.element_count());o<<"<Points><DataArray type=\"Float64\" NumberOfComponents=\"3\" format=\"ascii\">\n";for(auto n:m.nodes)o<<n.x<<' '<<n.y<<" 0\n";o<<"</DataArray></Points>\n<Cells><DataArray type=\"Int64\" Name=\"connectivity\" format=\"ascii\">\n";for(auto t:m.triangles)o<<t.node[0]<<' '<<t.node[1]<<' '<<t.node[2]<<'\n';o<<"</DataArray><DataArray type=\"Int64\" Name=\"offsets\" format=\"ascii\">\n";for(std::size_t i=1;i<=m.element_count();++i)o<<3*i<<' ';o<<"\n</DataArray><DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n";for(std::size_t i=0;i<m.element_count();++i)o<<"5 ";o<<"\n</DataArray></Cells>\n";if(!scalar.empty()){o<<"<PointData Scalars=\""<<name<<"\"><DataArray type=\"Float64\" Name=\""<<name<<"\" format=\"ascii\">\n";for(double x:scalar)o<<x<<' ';o<<"\n</DataArray></PointData>\n";}o<<"</Piece></UnstructuredGrid></VTKFile>\n";}
void write_vtu(const std::filesystem::path&p,const cfd::fem::Mesh3D&m,const std::vector<double>& scalar,std::string name){if(!scalar.empty()&&scalar.size()!=m.node_count())throw std::invalid_argument("VTU scalar size mismatch");std::ofstream o(p);if(!o)throw std::runtime_error("cannot create VTU");o<<std::setprecision(17);vtu_header(o,m.node_count(),m.element_count());o<<"<Points><DataArray type=\"Float64\" NumberOfComponents=\"3\" format=\"ascii\">\n";for(auto n:m.nodes)o<<n.x<<' '<<n.y<<' '<<n.z<<'\n';o<<"</DataArray></Points>\n<Cells><DataArray type=\"Int64\" Name=\"connectivity\" format=\"ascii\">\n";for(auto t:m.tetrahedra)o<<t.node[0]<<' '<<t.node[1]<<' '<<t.node[2]<<' '<<t.node[3]<<'\n';o<<"</DataArray><DataArray type=\"Int64\" Name=\"offsets\" format=\"ascii\">\n";for(std::size_t i=1;i<=m.element_count();++i)o<<4*i<<' ';o<<"\n</DataArray><DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n";for(std::size_t i=0;i<m.element_count();++i)o<<"10 ";o<<"\n</DataArray></Cells>\n";if(!scalar.empty()){o<<"<PointData Scalars=\""<<name<<"\"><DataArray type=\"Float64\" Name=\""<<name<<"\" format=\"ascii\">\n";for(double x:scalar)o<<x<<' ';o<<"\n</DataArray></PointData>\n";}o<<"</Piece></UnstructuredGrid></VTKFile>\n";}

cfd::fem::Mesh2D read_vtu_tri2d(const std::filesystem::path&p){
    std::ifstream in(p);if(!in)throw std::runtime_error("cannot open VTU");std::ostringstream os;os<<in.rdbuf();const std::string text=os.str();
    auto array=[&](const std::string& marker){auto pos=text.find(marker);if(pos==std::string::npos)throw std::runtime_error("VTU DataArray not found: "+marker);pos=text.find('>',pos);auto end=text.find("</DataArray>",pos);if(pos==std::string::npos||end==std::string::npos)throw std::runtime_error("malformed VTU DataArray");return text.substr(pos+1,end-pos-1);};
    cfd::fem::Mesh2D m;{std::istringstream ss(array("NumberOfComponents=\"3\""));double x,y,z;while(ss>>x>>y>>z)m.nodes.push_back({x,y});}
    std::vector<std::size_t> conn,offset;{std::istringstream ss(array("Name=\"connectivity\""));std::size_t x;while(ss>>x)conn.push_back(x);}{std::istringstream ss(array("Name=\"offsets\""));std::size_t x;while(ss>>x)offset.push_back(x);}std::size_t prev=0;for(auto end:offset){if(end-prev!=3||end>conn.size())throw std::runtime_error("VTU contains non-Tri3 cell");m.triangles.push_back({{conn[prev],conn[prev+1],conn[prev+2]}});prev=end;}
    m.boundary_node.assign(m.nodes.size(),0);std::unordered_map<std::uint64_t,int> edge_count;auto key=[](std::size_t a,std::size_t b){if(a>b)std::swap(a,b);return (static_cast<std::uint64_t>(a)<<32)|static_cast<std::uint64_t>(b);};for(const auto&t:m.triangles)for(int e=0;e<3;++e)++edge_count[key(t.node[e],t.node[(e+1)%3])];for(const auto&t:m.triangles)for(int e=0;e<3;++e){auto a=t.node[e],b=t.node[(e+1)%3];if(edge_count[key(a,b)]==1){m.boundary_edges.push_back({{a,b},0});m.boundary_node[a]=m.boundary_node[b]=1;}}m.validate();return m;
}
} // namespace cfd::io
